spring:
  application:
    name: hello-service

server:
  port: ${PORT:0}


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
