spring:
  application:
    name: currency-conversion-service

server:
  port: 9999


#currency-exchange-service:
  #  ribbon:
  #    listOfServers: http://localhost:8888,http://localhost:8889

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka