spring:
  application:
    name: hello-service
server:
  port: ${PORT:8090}
  #eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      metadataMap:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



