server:
  port: 2020
  servlet:
    context-path: /SIMS/hello-service/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    appname: hello-service
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 10

spring:
  application: 
    name: hello-service