spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: C:/Users/luisa.suraci/OneDrive - Accenture/Sviluppo/formazione/udemy/in28minutes/git-config-repo
        bootstrap: true

server:
  port: 8080